
version: "3.9"

# docker-compose --env-file ./env/env.dev --file ./container/docker-compose.yml up -d
# docker-compose --env-file ./env/env.dev --file ./container/docker-compose.yml up -d db_mongo
# docker-compose --env-file ./env/env.dev --file ./container/docker-compose.yml down --remove-orphans

services:
  core_parent_with_gradle:
    image: core_parent_with_gradle
    build:
      context: ../
      dockerfile: container/core-parent-image.Dockerfile

  db_mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${LOCAL_SPRING_DATA_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${LOCAL_SPRING_DATA_MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${LOCAL_SPRING_DATA_MONGODB_DATABASE}
    ports:
      - 27017:${LOCAL_SPRING_DATA_MONGODB_PORT}

  ms_account:
    container_name: ms_account_container
    image: ms_account
    depends_on: 
      - core_parent_with_gradle
    links:
      - db_mongo:local.mongo
    build:
      context: ../
      dockerfile: container/microservices.Dockerfile
      args:
        NAME_PROJECT: account-ms
        SOURCE_APP_PATH: microservices/account-ms
        PORT_APP: ${ACCOUNT_SERVER_PORT}
        JVM_ARGS: -Xmx150M -Xms60M
    environment:
      ACCOUNT_SERVER_PORT: ${ACCOUNT_SERVER_PORT}
      SECRET_JWT: ${SECRET_JWT}
      LOGGING_LEVEL_APICORE_INTEGRATION: ${LOGGING_LEVEL_APICORE_INTEGRATION}
      LOGGING_LEVEL_ACCOUNT: ${LOGGING_LEVEL_ACCOUNT}
      LOGGING_PATTERN_CONSOLE: ${LOGGING_PATTERN_CONSOLE}
      ACCOUNT_SPRING_DATA_MONGODB_HOST: local.mongo
      ACCOUNT_SPRING_DATA_MONGODB_PORT: ${ACCOUNT_SPRING_DATA_MONGODB_PORT}
      ACCOUNT_SPRING_DATA_MONGODB_DATABASE: ${ACCOUNT_SPRING_DATA_MONGODB_DATABASE}
      ACCOUNT_SPRING_DATA_MONGODB_USERNAME: ${ACCOUNT_SPRING_DATA_MONGODB_USERNAME}
      ACCOUNT_SPRING_DATA_MONGODB_PASSWORD: ${ACCOUNT_SPRING_DATA_MONGODB_PASSWORD}
      ACCOUNT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: ${ACCOUNT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    ports:
      - ${ACCOUNT_SERVER_PORT}:${ACCOUNT_SERVER_PORT}

  ms_session:
    container_name: ms_session_container
    image: ms_session
    depends_on: 
      - core_parent_with_gradle
    links:
      - db_mongo:local.mongo
      - ms_account:localhost.account
    build:
      context: ../
      dockerfile: container/microservices.Dockerfile
      args:
        NAME_PROJECT: session-ms
        SOURCE_APP_PATH: microservices/session-ms
        PORT_APP: ${SESSION_SERVER_PORT}
        JVM_ARGS: -Xmx150M -Xms60M
    environment:
      SESSION_SERVER_PORT: ${SESSION_SERVER_PORT}
      ACCOUNT_MS_ENDPOINT: http://localhost.account:${ACCOUNT_SERVER_PORT}
      SECRET_JWT: ${SECRET_JWT}
      LOGGING_LEVEL_APICORE_INTEGRATION: ${LOGGING_LEVEL_APICORE_INTEGRATION}
      LOGGING_LEVEL_SESSION: ${LOGGING_LEVEL_SESSION}
      LOGGING_PATTERN_CONSOLE: ${LOGGING_PATTERN_CONSOLE}
      SESSION_SPRING_DATA_MONGODB_HOST: local.mongo
      SESSION_SPRING_DATA_MONGODB_PORT: ${SESSION_SPRING_DATA_MONGODB_PORT}
      SESSION_SPRING_DATA_MONGODB_DATABASE: ${SESSION_SPRING_DATA_MONGODB_DATABASE}
      SESSION_SPRING_DATA_MONGODB_USERNAME: ${SESSION_SPRING_DATA_MONGODB_USERNAME}
      SESSION_SPRING_DATA_MONGODB_PASSWORD: ${SESSION_SPRING_DATA_MONGODB_PASSWORD}
      SESSION_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: ${SESSION_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    ports:
      - ${SESSION_SERVER_PORT}:${SESSION_SERVER_PORT}

  ms_content_add_event:
    container_name: ms_content_add_event_container
    image: ms_content_add_event
    depends_on: 
      - core_parent_with_gradle
    links:
      - db_mongo:local.mongo
    build:
      context: ../
      dockerfile: container/microservices.Dockerfile
      args:
        NAME_PROJECT: content-add-event-ms
        SOURCE_APP_PATH: microservices/content-add-event-ms
        PORT_APP: ${CONTENT_ADD_EVENT_SERVER_PORT}
        JVM_ARGS: -Xmx150M -Xms60M
    environment:
      CONTENT_ADD_EVENT_SERVER_PORT: ${CONTENT_ADD_EVENT_SERVER_PORT}
      SECRET_JWT: ${SECRET_JWT}
      LOGGING_LEVEL_APICORE_INTEGRATION: ${LOGGING_LEVEL_APICORE_INTEGRATION}
      LOGGING_LEVEL_CONTENTADDEVENT: ${LOGGING_LEVEL_CONTENTADDEVENT}
      LOGGING_PATTERN_CONSOLE: ${LOGGING_PATTERN_CONSOLE}
      CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_HOST: local.mongo
      CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_PORT: ${CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_PORT}
      CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_DATABASE: ${CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_DATABASE}
      CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_USERNAME: ${CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_USERNAME}
      CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_PASSWORD: ${CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_PASSWORD}
      CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: ${CONTENT_ADD_EVENT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    ports:
      - ${CONTENT_ADD_EVENT_SERVER_PORT}:${CONTENT_ADD_EVENT_SERVER_PORT}

  ms_content_on_hot_event:
    container_name: ms_content_on_hot_event_container
    image: ms_content_on_hot_event
    depends_on: 
      - core_parent_with_gradle
    links:
      - db_mongo:local.mongo
    build:
      context: ../
      dockerfile: container/microservices.Dockerfile
      args:
        NAME_PROJECT: content-on-hot-event-ms
        SOURCE_APP_PATH: microservices/content-on-hot-event-ms
        PORT_APP: ${CONTENT_ON_HOT_EVENT_SERVER_PORT}
        JVM_ARGS: -Xmx150M -Xms60M
    environment:
      CONTENT_ON_HOT_EVENT_SERVER_PORT: ${CONTENT_ON_HOT_EVENT_SERVER_PORT}
      SECRET_JWT: ${SECRET_JWT}
      LOGGING_LEVEL_APICORE_INTEGRATION: ${LOGGING_LEVEL_APICORE_INTEGRATION}
      LOGGING_LEVEL_CONTENTONHOTEVENT: ${LOGGING_LEVEL_CONTENTONHOTEVENT}
      LOGGING_PATTERN_CONSOLE: ${LOGGING_PATTERN_CONSOLE}
      CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_HOST: local.mongo
      CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_PORT: ${CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_PORT}
      CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_DATABASE: ${CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_DATABASE}
      CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_USERNAME: ${CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_USERNAME}
      CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_PASSWORD: ${CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_PASSWORD}
      CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: ${CONTENT_ON_HOT_EVENT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    ports:
      - ${CONTENT_ON_HOT_EVENT_SERVER_PORT}:${CONTENT_ON_HOT_EVENT_SERVER_PORT}

  ms_document_draft:
    container_name: ms_document_draft_container
    image: ms_document_draft
    depends_on: 
      - core_parent_with_gradle
    links:
      - db_mongo:local.mongo
    build:
      context: ../
      dockerfile: container/microservices.Dockerfile
      args:
        NAME_PROJECT: document-draft-ms
        SOURCE_APP_PATH: microservices/document-draft-ms
        PORT_APP: ${DOCUMENT_DRAFT_SERVER_PORT}
        JVM_ARGS: -Xmx150M -Xms60M
    environment:
      DOCUMENT_DRAFT_SERVER_PORT: ${DOCUMENT_DRAFT_SERVER_PORT}
      SECRET_JWT: ${SECRET_JWT}
      LOGGING_LEVEL_APICORE_INTEGRATION: ${LOGGING_LEVEL_APICORE_INTEGRATION}
      LOGGING_LEVEL_DOCUMENTDRAFT: ${LOGGING_LEVEL_DOCUMENTDRAFT}
      LOGGING_PATTERN_CONSOLE: ${LOGGING_PATTERN_CONSOLE}
      DOCUMENT_DRAFT_SPRING_DATA_MONGODB_HOST: local.mongo
      DOCUMENT_DRAFT_SPRING_DATA_MONGODB_PORT: ${DOCUMENT_DRAFT_SPRING_DATA_MONGODB_PORT}
      DOCUMENT_DRAFT_SPRING_DATA_MONGODB_DATABASE: ${DOCUMENT_DRAFT_SPRING_DATA_MONGODB_DATABASE}
      DOCUMENT_DRAFT_SPRING_DATA_MONGODB_USERNAME: ${DOCUMENT_DRAFT_SPRING_DATA_MONGODB_USERNAME}
      DOCUMENT_DRAFT_SPRING_DATA_MONGODB_PASSWORD: ${DOCUMENT_DRAFT_SPRING_DATA_MONGODB_PASSWORD}
      DOCUMENT_DRAFT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: ${DOCUMENT_DRAFT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    ports:
      - ${DOCUMENT_DRAFT_SERVER_PORT}:${DOCUMENT_DRAFT_SERVER_PORT}


  ms_document_publish:
    container_name: ms_document_publish_container
    image: ms_document_publish
    depends_on: 
      - core_parent_with_gradle
    links:
      - db_mongo:local.mongo
    build:
      context: ../
      dockerfile: container/microservices.Dockerfile
      args:
        NAME_PROJECT: document-publish-ms
        SOURCE_APP_PATH: microservices/document-publish-ms
        PORT_APP: ${DOCUMENT_PUBLISH_SERVER_PORT}
        JVM_ARGS: -Xmx150M -Xms60M
    environment:
      DOCUMENT_PUBLISH_SERVER_PORT: ${DOCUMENT_PUBLISH_SERVER_PORT}
      SECRET_JWT: ${SECRET_JWT}
      LOGGING_LEVEL_APICORE_INTEGRATION: ${LOGGING_LEVEL_APICORE_INTEGRATION}
      LOGGING_LEVEL_DOCUMENTPUBLISH: ${LOGGING_LEVEL_DOCUMENTPUBLISH}
      LOGGING_PATTERN_CONSOLE: ${LOGGING_PATTERN_CONSOLE}
      DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_HOST: local.mongo
      DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_PORT: ${DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_PORT}
      DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_DATABASE: ${DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_DATABASE}
      DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_USERNAME: ${DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_USERNAME}
      DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_PASSWORD: ${DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_PASSWORD}
      DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: ${DOCUMENT_PUBLISH_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    ports:
      - ${DOCUMENT_PUBLISH_SERVER_PORT}:${DOCUMENT_PUBLISH_SERVER_PORT}


  ms_document:
    container_name: ms_document_container
    image: ms_document
    depends_on: 
      - core_parent_with_gradle
    links:
      - db_mongo:local.mongo
    build:
      context: ../
      dockerfile: container/microservices.Dockerfile
      args:
        NAME_PROJECT: document-ms
        SOURCE_APP_PATH: microservices/document-ms
        PORT_APP: ${DOCUMENT_SERVER_PORT}
        JVM_ARGS: -Xmx150M -Xms60M
    environment:
      DOCUMENT_SERVER_PORT: ${DOCUMENT_SERVER_PORT}
      SECRET_JWT: ${SECRET_JWT}
      LOGGING_LEVEL_APICORE_INTEGRATION: ${LOGGING_LEVEL_APICORE_INTEGRATION}
      LOGGING_LEVEL_DOCUMENT: ${LOGGING_LEVEL_DOCUMENT}
      LOGGING_PATTERN_CONSOLE: ${LOGGING_PATTERN_CONSOLE}
      DOCUMENT_SPRING_DATA_MONGODB_HOST: local.mongo
      DOCUMENT_SPRING_DATA_MONGODB_PORT: ${DOCUMENT_SPRING_DATA_MONGODB_PORT}
      DOCUMENT_SPRING_DATA_MONGODB_DATABASE: ${DOCUMENT_SPRING_DATA_MONGODB_DATABASE}
      DOCUMENT_SPRING_DATA_MONGODB_USERNAME: ${DOCUMENT_SPRING_DATA_MONGODB_USERNAME}
      DOCUMENT_SPRING_DATA_MONGODB_PASSWORD: ${DOCUMENT_SPRING_DATA_MONGODB_PASSWORD}
      DOCUMENT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: ${DOCUMENT_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    ports:
      - ${DOCUMENT_SERVER_PORT}:${DOCUMENT_SERVER_PORT}

  ms_storage:
    container_name: ms_storage_container
    image: ms_storage
    depends_on: 
      - core_parent_with_gradle
    links:
      - db_mongo:local.mongo
    build:
      context: ../
      dockerfile: container/microservices.Dockerfile
      args:
        NAME_PROJECT: storage-ms
        SOURCE_APP_PATH: microservices/storage-ms
        PORT_APP: ${STORAGE_SERVER_PORT}
        JVM_ARGS: -Xmx150M -Xms60M
    environment:
      STORAGE_SERVER_PORT: ${STORAGE_SERVER_PORT}
      SECRET_JWT: ${SECRET_JWT}
      LOGGING_LEVEL_APICORE_INTEGRATION: ${LOGGING_LEVEL_APICORE_INTEGRATION}
      LOGGING_LEVEL_STORAGE: ${LOGGING_LEVEL_STORAGE}
      LOGGING_PATTERN_CONSOLE: ${LOGGING_PATTERN_CONSOLE}
      STORAGE_SPRING_DATA_MONGODB_HOST: local.mongo
      STORAGE_SPRING_DATA_MONGODB_PORT: ${STORAGE_SPRING_DATA_MONGODB_PORT}
      STORAGE_SPRING_DATA_MONGODB_DATABASE: ${STORAGE_SPRING_DATA_MONGODB_DATABASE}
      STORAGE_SPRING_DATA_MONGODB_USERNAME: ${STORAGE_SPRING_DATA_MONGODB_USERNAME}
      STORAGE_SPRING_DATA_MONGODB_PASSWORD: ${STORAGE_SPRING_DATA_MONGODB_PASSWORD}
      STORAGE_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: ${STORAGE_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    ports:
      - ${STORAGE_SERVER_PORT}:${STORAGE_SERVER_PORT}